name: Build OnSpace APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: JaxL9/TAP-A-Cusor
          path: app-folder

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd app-folder
          npm install --force

      - name: Build APK
        # Changed @v2 to @main to fix "unable to install" error
        uses: ni554n/apk-builder-action@main 
        with:
          root-directory: ./app-folder
